# Setup
version_name: MLoRE_nyud_vitLp16
out_dir: "./"

# Database
train_db_name: NYUD
val_db_name: NYUD
trBatch: 2
valBatch: 6
nworkers: 2
ignore_index: 255

# Optimizer and scheduler
intermediate_supervision: False
val_interval: 2000
epochs: 999999
max_iter: 40000
optimizer: adam
optimizer_kwargs:
   lr: 0.00001
   weight_decay: 1.e-6
scheduler: poly
grad_clip_param: {'max_norm': 10, 'norm_type': 2}
ignore_invalid_area_depth: True

# Model
model: MLoRE
backbone: MLoRE_vitL_repara
head:  conv
final_embed_dim: 768
rank_list:  [16, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224, 240]
spe_rank: 16
topk: 9
pre_softmax: True

# Tasks
task_dictionary:
   include_semseg: True
   include_depth: True
   include_edge: True
   include_normals: True
   edge_w: 0.88

# Loss kwargs
loss_kwargs:
   loss_weights:
       semseg: 1.0
       depth: 1.0
       normals: 10
       edge: 50.0
       load_balancing: 0.0005
