# Setup
version_name: MLoRE_pascal_vitSp16
out_dir: "./"

# Database
train_db_name: PASCALContext
val_db_name: PASCALContext
trBatch: 2
valBatch: 6
nworkers: 2
ignore_index: 255

# Optimizer and scheduler
intermediate_supervision: False
val_interval: 2000
epochs: 999999
max_iter: 40000
optimizer: adam
optimizer_kwargs:
   lr: 0.00002
   weight_decay: 0.000001
scheduler: poly
grad_clip_param: {'max_norm': 10, 'norm_type': 2}

# Model
model: MLoRE
backbone: MLoRE_vitS
head:  conv
final_embed_dim: 192
rank_list: [8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64]
spe_rank: 32
topk: 9

# Tasks
task_dictionary:
   include_semseg: True
   include_human_parts: True
   include_sal: True
   include_edge: True
   include_normals: True
   edge_w: 0.95

# Loss kwargs
loss_kwargs:
   loss_weights:
       semseg: 1.0
       human_parts: 2.0
       sal: 5.0
       edge: 50.0
       normals: 10.0
       load_balancing: 0.0001
